### ISSUE TITLE
US4 - New Game question after finishing

### ISSUE THREAD

**Issue by ChristophLeuker** [ChristophLeuker/Capstone-project-Throw-In-App#1]
## Value Proposition

**As a** user
**I want to** be able to play again after a round
**so that** i can choose to play another round with same settings
​

## Description

![Image](https://github.com/ChristophLeuker/journal-app/assets/131157050/a2515761-bb8b-45eb-bab1-3e93e384e064)

​

## Acceptance Criteria

- [ ] get a Pop-up with the information who wins and in how many darts
- [ ] get the question to play again
- [ ] if 'yes' the scoreboard should be empty to play again
- [ ] if 'no' the pop-up should close

      ​

## Tasks

- [ ] create branch newgamequestion
- [ ] create a newGameQuestion component
- [ ] add a Pop-up with the text who wins and how many darts are thrown.
- [ ] add two buttons to either play again (delete the last game) or not (just close the pop-up)
- [ ] write the function for the pop-up to shown when one 'ToGo' field is 0.
- [ ] write the function for 'Yes' Button to empty the scoreboard and be able to play again
- [ ] write the function for 'No' Button to just close the pop-up.
- [ ] styling with style components
- [ ] render the component in the 501Game Page
