### ISSUE TITLE
US7 - Create MongoDB

### ISSUE THREAD

**Issue by ChristophLeuker** [ChristophLeuker/Capstone-project-Throw-In-App#12]
## Value Proposition

**As a** developer
**I want to** set up a MongoDB 
**so that** i can save the profile settings global
​

## Description

Set up a simple MongoDB to save the dates from my Create New Player Form with 
playername:
playerpassword:
playeremail:

​

## Acceptance Criteria

- [x] use MondoDB for saving informations for Player Profiles

      ​

## Tasks

- [x] setUp MongoDB Compass with collection "Player Infos"
- [x] connect it to MongoDB Atlas
- [x] save the datas from the Create New Player Form in the DB
- [x] write the POST command for that

**Comment by ryliecc** [comment]
LGTM, just one thing, User Stories are written for users, therefore we always put something like `**As a** user` in the beginning. I understand why you didn't though. Maybe send it to one of our amazing coaches to make sure. :)
