### ISSUE TITLE
US8 - Admin Page to control Players Profiles

### ISSUE THREAD

**Issue by ChristophLeuker** [ChristophLeuker/Capstone-project-Throw-In-App#13]
## Value Proposition

**As a** user
**I want to** be able to play again after a round
**so that** i can choose to play another round with same settings
​

## Description

![Image](https://user-images.githubusercontent.com/131157050/249476877-ba09492e-cb3d-471a-8131-60121ba96fa1.png)

​

## Acceptance Criteria

- [ ]  see a Headline
- [ ]  see a List of all Player Profiles with name and e-mail in the DB
- [ ]  have a Button to go back to the Mainpage
- [ ]  screen is vertical scrollable if there are to much information
      ​

## Tasks

- [ ] create branch profileoverview
- [ ] write the GET logic for the DB
- [ ] write the Headline
- [ ] write the logic to get a card for every player
- [ ] show all cards the page as List items
- [ ] add a Button to go back to the Mainpage

**Comment by TmWgnr** [comment]
hi Christoph, 
I´m not sure but I think your Value Proposition does not fit with your Criteria&Tasks?

**Comment by ChristophLeuker** [comment]
oh yes sure, my mistake. just copied from an older US :D

**Comment by TmWgnr** [comment]
seems to be fitted now :D 
good scope. nothing to add ;)
