### ISSUE TITLE
US1 - Fixed Game Demo

### ISSUE THREAD

**Issue by ChristophLeuker** [ChristophLeuker/Capstone-project-Throw-In-App#2]
## Value Proposition

**As a** user
**I want to** see a scoreboard  
**so that** i can see how i can write my match
​

## Description

![Image](https://user-images.githubusercontent.com/131157050/247903521-d79a8c98-8062-487a-8041-913fb40c7cbf.png)

​

## Acceptance Criteria

- [ ] see a fixed match of 501 D.O.
- [ ] a header with the game type is visible
- [ ] screen is vertical scrollable if table is longer than the screen
      ​

## Tasks

- [ ] create branch 501Game
- [ ] create Page/501Game
- [ ] create a header with the game type
- [ ] add a tabel with 4 columns and 11 rows
- [ ] add two text fields for who is playing
- [ ] add dummy data for all fields
      ​
