### ISSUE TITLE
US2 - Make the table interactive

### ISSUE THREAD

**Issue by ChristophLeuker** [ChristophLeuker/Capstone-project-Throw-In-App#3]
## Value Proposition

**As a** user
**I want to** see a scoreboard  
**so that** i can write my points into that
​

## Description

![Image](https://github.com/ChristophLeuker/journal-app/assets/131157050/f6eed408-3c22-4e65-977f-bcc6fbc1ee60)

​

## Acceptance Criteria

- [ ] write into the text-fields under 'scored'
- [ ] under 'to go' i see the points i have left
- [ ] a header with the game type is visible
- [ ] screen is vertical scrollable if table is longer than the screen

      ​

## Tasks

- [ ] create branch 501GameInteractive
- [ ] delete the dummy data
- [ ] add number-fields for the score
- [ ] add function that the 'to-go' field will be filled automatic after writing the score
- [ ] add 5 more rows
